---
ansible_user: admin
ansible_ssh_pass: admin

cli:
  username:  "{{ansible_user}}"
  password:  "{{ansible_ssh_pass}}"
  host:      "{{ansible_host|default(inventory_hostname)}}"
  transport: nxapi

repository: ./backup 
archive: ./archive
