---
- name: Inside VLANS Add
  hosts: inside
  tasks:
  - include_vars:
      file: "{{list|default(inventory_dir~'/list.yml')}}"
      name: "list"
    tags: [ always ] 


  - name: Add VLANs to vdc INSIDE
    nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      name:    "{{item.name}}"
      state:   "present"
      admin_state: "up"
    with_items: "{{list.vlans}}"
    when: item.vdc == "INSIDE"
    tags: [ add_vlan ]

  - name: Add vlan to trunk
    nxos_switchport:
      interface: item[1].portnumber
      mode: trunk
      trunk_vlans: "{{item[0].id}}"
    with_nested:
      - "{{ list.vlans }}"
      - "{{ list.ports }}"
    when: item[0].vdc == "INSIDE"
