---
- name: Inside VLANS Add
  hosts: all
  tasks:
  - include_vars:
      file: "{{list|default(inventory_dir~'/list.yml')}}"
      name: "list"


  - name: Add VLANs to vdc INSIDE
    nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      name:    "{{item.name}}"
      state:   "present"
      admin_state: "up"
    with_items: "{{list.vlans}}"
    when: item.vdc == "INSIDE"


  - name: Add VLANs to vdc Outside
    nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      name:    "{{item.name}}"
      state:   "present"
      admin_state: "up"
    with_items: "{{list.vlans}}"
    when: item.vdc == "OUTSIDE"

  - name: Add vlan to trunk
    nxos_switchport:
      interface: eth2/33
      mode: trunk
      trunk_vlans: "{{item.id}}"
    with_items: "{{outside.vlans}}"
    when: "item.id"
