---
- name: Inside VLANS Add
  hosts: inside
  tasks:
  - include_vars:
      file: "{{inside|default(inventory_dir~'/list-in.yml')}}"
      name: "inside"
    tags: [ always ] 


  - name: Add VLANs to vdc INSIDE
    nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      name:    "{{item.name}}"
      state:   "present"
      admin_state: "up"
    with_items: "{{inside.vlans}}"
  tags: [inside]

- name: Outside VLANS
  hosts: outside
  tasks:
  - include_vars:
      file: "{{outside|default(inventory_dir~'/list-out.yml')}}"
      name: "outside"
    tags: [ always ] 

  - name: Add VLANs to vdc Outside
    nxos_vlan:
      provider: "{{cli}}"
      vlan_id: "{{item.id}}" 
      name:    "{{item.name}}"
      state:   "present"
      admin_state: "up"
    with_items: "{{outside.vlans}}"
  tags: [outside]

  - name: Add vlan to trunk
    nxos_switchport:
      interface: eth2/33
      mode: trunk
      trunk_vlans: "{{item.id}}"
    with_items: "{{outside.vlans}}"
    when: "item.id"
